<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE studentgrade[
<!ELEMENT studentgrade (ID,Student,Maths,English,IT)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Student (#PCDATA)>
<!ELEMENT Maths (Test1,Test2)>
<!ELEMENT Test1 (#PCDATA)>
<!ELEMENT Test2 (#PCDATA)>

<!ELEMENT English (Essay1,Essay2)>
<!ELEMENT Essay1 (#PCDATA)>
<!ELEMENT Essay2 (#PCDATA)>

<!ELEMENT IT (Activity1,Test_2,Essay3)>
<!ELEMENT Activity1 (#PCDATA)>
<!ELEMENT Test_2 (#PCDATA)>
<!ELEMENT Essay3 (#PCDATA)>
]>

<studentgrade>


<ID>16430122-1521></ID>
<Student>Place,Camden G.</Student>
<Maths>
<Test1>54%</Test1>
<Test2>63%</Test2>
</Maths>

<English>
<Essay1>C+</Essay1>
<Essay2>B+</Essay2>
</English>

<IT>
<Activity1>Pass</Activity1>
<Test_2>32%</Test_2>
<Essay3>C+</Essay3>
</IT>



</studentgrade>